version: "3.9"

services:
  postgres:
    container_name: finances_database
    image: postgres:14.2-alpine
    env_file:
      - .env
    ports:
      - 5000:5432

  finances-api:
    build: .
    container_name: finances_api
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:rw
